SPLIT_KEYBOARD = yes
RGBLIGHT_ENABLE = yes
SPLIT_RGB_ENABLE = yes

KEYBOARD_LANGUAGE = jp
OLED_DRIVER_ENABLE = yes
SPLIT_LAYER_STATE_ENABLE = yes

BOOTLOADER = caterina
VIA_ENABLE = yes

# まだなら追加
LTO_ENABLE = no

# 使ってなければ全部 no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = no
